PUT http://localhost:5243/breakfasts/0e92891a-2a3c-42ad-b841-8ce69d9aa9be
Content-Type: application/json

{
    "id": "0e92891a-2a3c-42ad-b841-8ce69d9aa9be",
    "name": "Vegan Sunshine #2",
    "description": "Vegan everything! Join us for a healthy breakfast..",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}